language: node_js{{#native}}
env:
  - CXX="g++-4.8"{{/native}}
node_js:
  - "4"
  - "5"
  - "6"
sudo: false{{#native}}
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
{{/native}}
